version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080" # Puerto de la aplicación
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: devsudb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5433" # Puerto de PostgreSQL
